### ISSUE TITLE
No ROM hash in project description

### ISSUE THREAD

**Issue by ghost** [shygoo/mk64extract#2]
Hello,

I can't get your project to work with my Mario Kart 64 ROM from the No-Intro set.
`e19398a0fd1cc12df64fca7fbcaa82cc  Mario Kart 64 (USA).n64`

Since you are using a `.z64` rom instead of a `.n64` one, I suggest you should provide the hash of the ROM you are working with in the `README.md`.

I also suggest you to switch to `.n64`, [it does matter.](http://jul.rustedlogic.net/thread.php?id=11769)

**Comment by shygoo** [comment]
I'd like to make it compatible with all of the byte orders and have it detect and swap to z64 on load because big endian is easiest to work with
